# Generated by Django 3.2.4 on 2021-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
